// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bankLedger/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACTIVE AccountStatus = 0
	AccountStatus_CLOSED AccountStatus = 1
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACTIVE": 0,
		"CLOSED": 1,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bankLedger_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_bankLedger_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{0}
}

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_INR                  Currency = 1
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "INR",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"INR":                  1,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_bankLedger_v1_account_proto_enumTypes[1].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_bankLedger_v1_account_proto_enumTypes[1]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{1}
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{0}
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{2}
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Currency      Currency               `protobuf:"varint,2,opt,name=currency,proto3,enum=bankLedger.v1.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Balance       string                 `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      Currency               `protobuf:"varint,5,opt,name=currency,proto3,enum=bankLedger.v1.Currency" json:"currency,omitempty"`
	Status        AccountStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=bankLedger.v1.AccountStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *AccountResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *AccountResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACTIVE
}

func (x *AccountResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetAllAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountResponse     `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountsResponse) Reset() {
	*x = GetAllAccountsResponse{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountsResponse) ProtoMessage() {}

func (x *GetAllAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAccountsResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllAccountsResponse) GetAccounts() []*AccountResponse {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        AccountStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=bankLedger.v1.AccountStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccountRequest) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACTIVE
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_bankLedger_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bankLedger_v1_account_proto protoreflect.FileDescriptor

const file_bankLedger_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1bbankLedger/v1/account.proto\x12\rbankLedger.v1\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fEmptyRequest\"\x1d\n" +
	"\vBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fBaseResponse\"_\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x17.bankLedger.v1.CurrencyR\bcurrency\"\x9c\x02\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\tR\raccountNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x04 \x01(\tR\abalance\x123\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x17.bankLedger.v1.CurrencyR\bcurrency\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.bankLedger.v1.AccountStatusR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"T\n" +
	"\x16GetAllAccountsResponse\x12:\n" +
	"\baccounts\x18\x01 \x03(\v2\x1e.bankLedger.v1.AccountResponseR\baccounts\"p\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.bankLedger.v1.AccountStatusR\x06status\"1\n" +
	"\x15DeleteAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*'\n" +
	"\rAccountStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x01*-\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03INR\x10\x012\xa6\x04\n" +
	"\aAccount\x12l\n" +
	"\rCreateAccount\x12#.bankLedger.v1.CreateAccountRequest\x1a\x1e.bankLedger.v1.AccountResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/account\x12b\n" +
	"\n" +
	"GetAccount\x12\x1a.bankLedger.v1.BaseRequest\x1a\x1e.bankLedger.v1.AccountResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/account/{id}\x12i\n" +
	"\x0eGetAllAccounts\x12\x1b.bankLedger.v1.EmptyRequest\x1a%.bankLedger.v1.GetAllAccountsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/account\x12q\n" +
	"\rUpdateAccount\x12#.bankLedger.v1.UpdateAccountRequest\x1a\x1e.bankLedger.v1.AccountResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/account/{id}\x12k\n" +
	"\rDeleteAccount\x12\x1a.bankLedger.v1.BaseRequest\x1a$.bankLedger.v1.DeleteAccountResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/account/{id}B]\n" +
	"\x1cdev.kratos.api.bankLedger.v1B\x11BankLedgerProtoV1P\x01Z(bank-ledger-service/api/bankLedger/v1;v1b\x06proto3"

var (
	file_bankLedger_v1_account_proto_rawDescOnce sync.Once
	file_bankLedger_v1_account_proto_rawDescData []byte
)

func file_bankLedger_v1_account_proto_rawDescGZIP() []byte {
	file_bankLedger_v1_account_proto_rawDescOnce.Do(func() {
		file_bankLedger_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bankLedger_v1_account_proto_rawDesc), len(file_bankLedger_v1_account_proto_rawDesc)))
	})
	return file_bankLedger_v1_account_proto_rawDescData
}

var file_bankLedger_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bankLedger_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bankLedger_v1_account_proto_goTypes = []any{
	(AccountStatus)(0),             // 0: bankLedger.v1.AccountStatus
	(Currency)(0),                  // 1: bankLedger.v1.Currency
	(*EmptyRequest)(nil),           // 2: bankLedger.v1.EmptyRequest
	(*BaseRequest)(nil),            // 3: bankLedger.v1.BaseRequest
	(*BaseResponse)(nil),           // 4: bankLedger.v1.BaseResponse
	(*CreateAccountRequest)(nil),   // 5: bankLedger.v1.CreateAccountRequest
	(*AccountResponse)(nil),        // 6: bankLedger.v1.AccountResponse
	(*GetAllAccountsResponse)(nil), // 7: bankLedger.v1.GetAllAccountsResponse
	(*UpdateAccountRequest)(nil),   // 8: bankLedger.v1.UpdateAccountRequest
	(*DeleteAccountResponse)(nil),  // 9: bankLedger.v1.DeleteAccountResponse
}
var file_bankLedger_v1_account_proto_depIdxs = []int32{
	1,  // 0: bankLedger.v1.CreateAccountRequest.currency:type_name -> bankLedger.v1.Currency
	1,  // 1: bankLedger.v1.AccountResponse.currency:type_name -> bankLedger.v1.Currency
	0,  // 2: bankLedger.v1.AccountResponse.status:type_name -> bankLedger.v1.AccountStatus
	6,  // 3: bankLedger.v1.GetAllAccountsResponse.accounts:type_name -> bankLedger.v1.AccountResponse
	0,  // 4: bankLedger.v1.UpdateAccountRequest.status:type_name -> bankLedger.v1.AccountStatus
	5,  // 5: bankLedger.v1.Account.CreateAccount:input_type -> bankLedger.v1.CreateAccountRequest
	3,  // 6: bankLedger.v1.Account.GetAccount:input_type -> bankLedger.v1.BaseRequest
	2,  // 7: bankLedger.v1.Account.GetAllAccounts:input_type -> bankLedger.v1.EmptyRequest
	8,  // 8: bankLedger.v1.Account.UpdateAccount:input_type -> bankLedger.v1.UpdateAccountRequest
	3,  // 9: bankLedger.v1.Account.DeleteAccount:input_type -> bankLedger.v1.BaseRequest
	6,  // 10: bankLedger.v1.Account.CreateAccount:output_type -> bankLedger.v1.AccountResponse
	6,  // 11: bankLedger.v1.Account.GetAccount:output_type -> bankLedger.v1.AccountResponse
	7,  // 12: bankLedger.v1.Account.GetAllAccounts:output_type -> bankLedger.v1.GetAllAccountsResponse
	6,  // 13: bankLedger.v1.Account.UpdateAccount:output_type -> bankLedger.v1.AccountResponse
	9,  // 14: bankLedger.v1.Account.DeleteAccount:output_type -> bankLedger.v1.DeleteAccountResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_bankLedger_v1_account_proto_init() }
func file_bankLedger_v1_account_proto_init() {
	if File_bankLedger_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bankLedger_v1_account_proto_rawDesc), len(file_bankLedger_v1_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bankLedger_v1_account_proto_goTypes,
		DependencyIndexes: file_bankLedger_v1_account_proto_depIdxs,
		EnumInfos:         file_bankLedger_v1_account_proto_enumTypes,
		MessageInfos:      file_bankLedger_v1_account_proto_msgTypes,
	}.Build()
	File_bankLedger_v1_account_proto = out.File
	file_bankLedger_v1_account_proto_goTypes = nil
	file_bankLedger_v1_account_proto_depIdxs = nil
}
