// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bankLedger/v1/transaction.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_DEPOSIT                      TransactionType = 1
	TransactionType_WITHDRAWAL                   TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "DEPOSIT",
		2: "WITHDRAWAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"DEPOSIT":                      1,
		"WITHDRAWAL":                   2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_bankLedger_v1_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_bankLedger_v1_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_INITIATED                      TransactionStatus = 1
	TransactionStatus_PROCESSING                     TransactionStatus = 2
	TransactionStatus_SUCCESS                        TransactionStatus = 3
	TransactionStatus_FAILED                         TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "INITIATED",
		2: "PROCESSING",
		3: "SUCCESS",
		4: "FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"INITIATED":                      1,
		"PROCESSING":                     2,
		"SUCCESS":                        3,
		"FAILED":                         4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bankLedger_v1_transaction_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_bankLedger_v1_transaction_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{1}
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=bankLedger.v1.TransactionType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=bankLedger.v1.TransactionStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateTransactionResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTransactionResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *CreateTransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTransactionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIdRequest) Reset() {
	*x = GetTransactionByIdRequest{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdRequest) ProtoMessage() {}

func (x *GetTransactionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionByIdRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type EachTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,4,opt,name=type,proto3,enum=bankLedger.v1.TransactionType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=bankLedger.v1.TransactionStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EachTransaction) Reset() {
	*x = EachTransaction{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EachTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EachTransaction) ProtoMessage() {}

func (x *EachTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EachTransaction.ProtoReflect.Descriptor instead.
func (*EachTransaction) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *EachTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EachTransaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *EachTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EachTransaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *EachTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EachTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *EachTransaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *EachTransaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EachTransaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TransactionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLog) Reset() {
	*x = TransactionLog{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLog) ProtoMessage() {}

func (x *TransactionLog) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLog.ProtoReflect.Descriptor instead.
func (*TransactionLog) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TransactionLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionLog) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *EachTransaction       `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Logs          []*TransactionLog      `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionResponse) GetTransaction() *EachTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionResponse) GetLogs() []*TransactionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetTransactionsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountRequest) Reset() {
	*x = GetTransactionsByAccountRequest{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountRequest) ProtoMessage() {}

func (x *GetTransactionsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionsByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetTransactionsByAccountRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsByAccountRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *PaginationInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *AccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTransactionsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Transactions  []*EachTransaction     `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	AccountInfo   *AccountInfo           `protobuf:"bytes,4,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountResponse) Reset() {
	*x = GetTransactionsByAccountResponse{}
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountResponse) ProtoMessage() {}

func (x *GetTransactionsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankLedger_v1_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_bankLedger_v1_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionsByAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetTransactionsByAccountResponse) GetTransactions() []*EachTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsByAccountResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTransactionsByAccountResponse) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

var File_bankLedger_v1_transaction_proto protoreflect.FileDescriptor

const file_bankLedger_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1fbankLedger/v1/transaction.proto\x12\rbankLedger.v1\x1a\x1cgoogle/api/annotations.proto\"\xa7\x01\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.bankLedger.v1.TransactionTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xba\x01\n" +
	"\x19CreateTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .bankLedger.v1.TransactionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"B\n" +
	"\x19GetTransactionByIdRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xc2\x02\n" +
	"\x0fEachTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.bankLedger.v1.TransactionTypeR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .bankLedger.v1.TransactionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"z\n" +
	"\x0eTransactionLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\"\x8d\x01\n" +
	"\x16GetTransactionResponse\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.bankLedger.v1.EachTransactionR\vtransaction\x121\n" +
	"\x04logs\x18\x02 \x03(\v2\x1d.bankLedger.v1.TransactionLogR\x04logs\"q\n" +
	"\x1fGetTransactionsByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\x0ePaginationInfo\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"k\n" +
	"\vAccountInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x83\x02\n" +
	" GetTransactionsByAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12B\n" +
	"\ftransactions\x18\x02 \x03(\v2\x1e.bankLedger.v1.EachTransactionR\ftransactions\x12=\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.bankLedger.v1.PaginationInfoR\n" +
	"pagination\x12=\n" +
	"\faccount_info\x18\x04 \x01(\v2\x1a.bankLedger.v1.AccountInfoR\vaccountInfo*P\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aDEPOSIT\x10\x01\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\x02*o\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tINITIATED\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xd1\x03\n" +
	"\vTransaction\x12\x82\x01\n" +
	"\x11CreateTransaction\x12'.bankLedger.v1.CreateTransactionRequest\x1a(.bankLedger.v1.CreateTransactionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/transaction\x12\x8f\x01\n" +
	"\x12GetTransactionById\x12(.bankLedger.v1.GetTransactionByIdRequest\x1a%.bankLedger.v1.GetTransactionResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/transaction/{transaction_id}\x12\xaa\x01\n" +
	"\x18GetTransactionsByAccount\x12..bankLedger.v1.GetTransactionsByAccountRequest\x1a/.bankLedger.v1.GetTransactionsByAccountResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/account/{account_id}/transactionsB]\n" +
	"\x1cdev.kratos.api.bankLedger.v1B\x11BankLedgerProtoV1P\x01Z(bank-ledger-service/api/bankLedger/v1;v1b\x06proto3"

var (
	file_bankLedger_v1_transaction_proto_rawDescOnce sync.Once
	file_bankLedger_v1_transaction_proto_rawDescData []byte
)

func file_bankLedger_v1_transaction_proto_rawDescGZIP() []byte {
	file_bankLedger_v1_transaction_proto_rawDescOnce.Do(func() {
		file_bankLedger_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bankLedger_v1_transaction_proto_rawDesc), len(file_bankLedger_v1_transaction_proto_rawDesc)))
	})
	return file_bankLedger_v1_transaction_proto_rawDescData
}

var file_bankLedger_v1_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bankLedger_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bankLedger_v1_transaction_proto_goTypes = []any{
	(TransactionType)(0),                     // 0: bankLedger.v1.TransactionType
	(TransactionStatus)(0),                   // 1: bankLedger.v1.TransactionStatus
	(*CreateTransactionRequest)(nil),         // 2: bankLedger.v1.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),        // 3: bankLedger.v1.CreateTransactionResponse
	(*GetTransactionByIdRequest)(nil),        // 4: bankLedger.v1.GetTransactionByIdRequest
	(*EachTransaction)(nil),                  // 5: bankLedger.v1.EachTransaction
	(*TransactionLog)(nil),                   // 6: bankLedger.v1.TransactionLog
	(*GetTransactionResponse)(nil),           // 7: bankLedger.v1.GetTransactionResponse
	(*GetTransactionsByAccountRequest)(nil),  // 8: bankLedger.v1.GetTransactionsByAccountRequest
	(*PaginationInfo)(nil),                   // 9: bankLedger.v1.PaginationInfo
	(*AccountInfo)(nil),                      // 10: bankLedger.v1.AccountInfo
	(*GetTransactionsByAccountResponse)(nil), // 11: bankLedger.v1.GetTransactionsByAccountResponse
}
var file_bankLedger_v1_transaction_proto_depIdxs = []int32{
	0,  // 0: bankLedger.v1.CreateTransactionRequest.type:type_name -> bankLedger.v1.TransactionType
	1,  // 1: bankLedger.v1.CreateTransactionResponse.status:type_name -> bankLedger.v1.TransactionStatus
	0,  // 2: bankLedger.v1.EachTransaction.type:type_name -> bankLedger.v1.TransactionType
	1,  // 3: bankLedger.v1.EachTransaction.status:type_name -> bankLedger.v1.TransactionStatus
	5,  // 4: bankLedger.v1.GetTransactionResponse.transaction:type_name -> bankLedger.v1.EachTransaction
	6,  // 5: bankLedger.v1.GetTransactionResponse.logs:type_name -> bankLedger.v1.TransactionLog
	5,  // 6: bankLedger.v1.GetTransactionsByAccountResponse.transactions:type_name -> bankLedger.v1.EachTransaction
	9,  // 7: bankLedger.v1.GetTransactionsByAccountResponse.pagination:type_name -> bankLedger.v1.PaginationInfo
	10, // 8: bankLedger.v1.GetTransactionsByAccountResponse.account_info:type_name -> bankLedger.v1.AccountInfo
	2,  // 9: bankLedger.v1.Transaction.CreateTransaction:input_type -> bankLedger.v1.CreateTransactionRequest
	4,  // 10: bankLedger.v1.Transaction.GetTransactionById:input_type -> bankLedger.v1.GetTransactionByIdRequest
	8,  // 11: bankLedger.v1.Transaction.GetTransactionsByAccount:input_type -> bankLedger.v1.GetTransactionsByAccountRequest
	3,  // 12: bankLedger.v1.Transaction.CreateTransaction:output_type -> bankLedger.v1.CreateTransactionResponse
	7,  // 13: bankLedger.v1.Transaction.GetTransactionById:output_type -> bankLedger.v1.GetTransactionResponse
	11, // 14: bankLedger.v1.Transaction.GetTransactionsByAccount:output_type -> bankLedger.v1.GetTransactionsByAccountResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_bankLedger_v1_transaction_proto_init() }
func file_bankLedger_v1_transaction_proto_init() {
	if File_bankLedger_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bankLedger_v1_transaction_proto_rawDesc), len(file_bankLedger_v1_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bankLedger_v1_transaction_proto_goTypes,
		DependencyIndexes: file_bankLedger_v1_transaction_proto_depIdxs,
		EnumInfos:         file_bankLedger_v1_transaction_proto_enumTypes,
		MessageInfos:      file_bankLedger_v1_transaction_proto_msgTypes,
	}.Build()
	File_bankLedger_v1_transaction_proto = out.File
	file_bankLedger_v1_transaction_proto_goTypes = nil
	file_bankLedger_v1_transaction_proto_depIdxs = nil
}
